# Generated by Django 5.1.1 on 2024-11-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='accept',
            name='name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
