# Generated by Django 5.1.1 on 2024-11-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_accept_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accept',
            old_name='name',
            new_name='day',
        ),
    ]
