# Generated by Django 5.1.1 on 2024-11-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0005_rename_name_accept_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accept',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='accept',
            name='time',
            field=models.TimeField(),
        ),
    ]
